### PR TITLE
import pin data from CSV

### PR DESCRIPTION
**Pull request by endofexclusive**
CSV feels more convenient since it can be generated directly from example LibreOffice Calc.

### CODE REVIEW

**Comment by carrotIndustries** [comment]
We should still keep json as it's supported.

**Comment by endofexclusive** [comment]
How about this? Hope it does not break the flow of the otherwise smooth tutorial/getting-started style of text. I was also thinking of inventing a new _Reference_ section which could describes file formats etc in a more formal way.

**Comment by carrotIndustries** [comment]
Regarding types of docs, https://www.divio.com/blog/documentation/ definitely is something we might consider to organize the documentation.

**Comment by atoav** [comment]
> Regarding types of docs, https://www.divio.com/blog/documentation/ definitely is something we might consider to organize the documentation.  

I actually read this shortly before the last time I went through the docs, so It might have had at least some influence. Thanks for bringing it up again.

**Pull request merged**
