### PR TITLE
Add solus installation instructions

### PR DESCRIPTION
**Pull request by maikwoehl**
Added installation instructions from unofficial sources.

A package request to the official repository will be filed in the next days.

### CODE REVIEW

**Comment by maikwoehl** [comment]
Output on local machine looks good.

**Comment by maikwoehl** [comment]
Package requested is filed: https://dev.getsol.us/T9908

**Comment by maikwoehl** [comment]
Package accepted for inclusion.
Inclusion patch uploaded: https://dev.getsol.us/D12153

**Comment by carrotIndustries** [comment]
Just wondering, why doesn't your install step call `make install`?

**Comment by maikwoehl** [comment]
> Just wondering, why doesn't your install step call `make install`?

Because I'm a new maintainer in solus ecosystem and still learning how to use the macros in package.yml correctly. I'm now tinkering with the PREFIX variable to point the installation to /usr instead of /usr/local

**Comment by carrotIndustries** [comment]
For reference, here's how it's done in the arch linux PKGBUILD:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=horizon-eda#n22
`make DESTDIR=$pkgdir PREFIX=/usr install install-man`

**Comment by maikwoehl** [comment]
> For reference, here's how it's done in the arch linux PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=horizon-eda#n22 `make DESTDIR=$pkgdir PREFIX=/usr install install-man`

Now I have done that, too. Thank you.

**Comment by carrotIndustries** [comment]
Now that it's in their repos, you should probably update the installation instructions accordingly.

**Comment by maikwoehl** [comment]
It has landed: https://dev.getsol.us/source/horizon-eda/

**Pull request closed without merging**
