### PR TITLE
Add eopkg install command for Solus

### PR DESCRIPTION
**Pull request by maikwoehl**
I've added the install command for current Solus release.

### CODE REVIEW

**Comment by maikwoehl** [comment]
The following package.yml will build horizon-eda for Solus:

```
name       : horizon-eda
version    : 2.1.0
release    : 1
source     :
    - https://github.com/horizon-eda/horizon/archive/refs/tags/v2.1.0.tar.gz : 2ba7a64ef0d8f22ad12e6a5a9c108f865eeb468f954f51ee5fbc03e6a847549a
license    : GPL-3.0-or-later
component  : office.scientific
summary    : Horizon is a free EDA package
homepage   : https://horizon-eda.org/
description: |
  Horizon EDA is an Electronic Design Automation package supporting an integrated end-to-end workflow for printed circuit board design including parts management and schematic entry.
clang : true
builddeps  :
  - pkgconfig(libcurl)
  - pkgconfig(gtkmm-3.0)
  - pkgconfig(librsvg-2.0)
  - pkgconfig(uuid)
  - pkgconfig(sqlite3)
  - pkgconfig(libzmq)
  - pkgconfig(glm)
  - pkgconfig(libgit2)
  - pkgconfig(libpodofo-0)
  - pkgconfig(libzip)
  - libboost-devel
  - opencascade-ce-devel
  - cppzmq-devel
  - glibc
  - binutils-gold
setup      : |
build      : |
    %make
install    : |
    %make_install
    mkdir -p $installdir/usr/bin
    ln -rs $installdir/usr/local/bin/horizon-eda $installdir/usr/bin/horizon-eda
    ln -rs $installdir/usr/local/bin/horizon-bin $installdir/usr/bin/horizon-bin
    mkdir -p $installdir/usr/local/share/man/man1
    install -m 644 $workdir/man/horizon-eda.1 $installdir/usr/local/share/man/man1/horizon-eda.1
    install -m 644 $workdir/man/horizon-imp.1 $installdir/usr/local/share/man/man1/horizon-imp.1
```

**Note:** Solus eopkg builds with --copy-dt-needed-entries. That does not work with ld.gold. Instead `/usr/share/defaults/eopkg/eopkg.conf` have to be copied to `/etc/eopkg/eopkg.conf` and the `ldflags` property has to be changed.

With the parameter `clang : true` it builds without error while having eopkg.conf standard configuration in place.

I will try to push horizon-eda to solus repository. For now I will add the package.yml to my fork repository.

**Comment by maikwoehl** [comment]
https://gist.github.com/maikwoehl/49bd996269116bf5aff599d7cb768f15

**Comment by maikwoehl** [comment]
https://github.com/maikwoehl/horizon-eopkg

Can now build eopkg with github actions and uploads it as artifact to CI page.

**Comment by maikwoehl** [comment]
Created Release v2.1.0 with eopkg: https://github.com/maikwoehl/horizon-eopkg/releases/tag/v2.1.0

**Comment by maikwoehl** [comment]
Feel free to fork repository.

**Comment by carrotIndustries** [comment]
> Can now build eopkg with github actions and uploads it as artifact to CI page.

I don't anything about solus, but maybe it's worth adding instructions to https://horizon-eda.readthedocs.io/en/latest/installation.html on how to install the binary packages.

**Pull request merged**
